export const motivosPorSeveridad = {
  Leve: ["No prestar atención al docente", 
          "Juegos no autorizados", 
          "Comportamiento irrespetuoso a compañeros",
          "Compartir propaganda no autorizada por Dirección",
          "Promocionar actividades en nombre de la Institución sin autorización",
          "Uso de dispositivos digitales en clase",
          "Portar gorras o sombreros sin autorización",
          "Ocasionar daño a recursos de la Institución",
          "Usar las computadoras de la Institución de manera indebida",],
  Severo: ["Posesión, distribución y consulta de contenido pornográfico",
           "Uso de lenguaje despectivo a compañeros", 
           "Agresión verbal a docente o personal escolar",
           "Falta de respeto a personal escolar",
           "Abandono de clase sin autorización",
           "Planear o participar en el abandono de clases (pinteada)",
           "Copiar en examen o pasar respuestas",],
  Grave: ["Agresión física a compañeros o personal escolar",
          "Causar o participar en vandalismo", 
          "Portación de armas blancas",
          "Portar, consumir y/o vender sustancias nocivas",
          "Sustracción de bienes de la Institución",
          "Dañar intencionalmente las instalaciones de la Institución",
          "Alterar firma de tutor",
          "Falsificar documentos institucionales"],
} as const;